package com.roger.ims.entity;

import java.util.Date;

/**  
* @Title: SysRight  
* @Description: 权限表 sys_right
* @author roger  
* @date 2019年7月17日  
*/  
public class SysRight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.right_id
     *
     * @mbg.generated
     */
    private Long rightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.right_name
     *
     * @mbg.generated
     */
    private String rightName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.parent_right
     *
     * @mbg.generated
     */
    private Long parentRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.right_level
     *
     * @mbg.generated
     */
    private Integer rightLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.menu_index
     *
     * @mbg.generated
     */
    private String menuIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.creation_time
     *
     * @mbg.generated
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.creation_user_id
     *
     * @mbg.generated
     */
    private Long creationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.last_update_user_id
     *
     * @mbg.generated
     */
    private Long lastUpdateUserId;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.right_id
     *
     * @return the value of sys_right.right_id
     *
     * @mbg.generated
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.right_id
     *
     * @param rightId the value for sys_right.right_id
     *
     * @mbg.generated
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.right_name
     *
     * @return the value of sys_right.right_name
     *
     * @mbg.generated
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.right_name
     *
     * @param rightName the value for sys_right.right_name
     *
     * @mbg.generated
     */
    public void setRightName(String rightName) {
        this.rightName = rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.parent_right
     *
     * @return the value of sys_right.parent_right
     *
     * @mbg.generated
     */
    public Long getParentRight() {
        return parentRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.parent_right
     *
     * @param parentRight the value for sys_right.parent_right
     *
     * @mbg.generated
     */
    public void setParentRight(Long parentRight) {
        this.parentRight = parentRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.right_level
     *
     * @return the value of sys_right.right_level
     *
     * @mbg.generated
     */
    public Integer getRightLevel() {
        return rightLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.right_level
     *
     * @param rightLevel the value for sys_right.right_level
     *
     * @mbg.generated
     */
    public void setRightLevel(Integer rightLevel) {
        this.rightLevel = rightLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.menu_index
     *
     * @return the value of sys_right.menu_index
     *
     * @mbg.generated
     */
    public String getMenuIndex() {
        return menuIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.menu_index
     *
     * @param menuIndex the value for sys_right.menu_index
     *
     * @mbg.generated
     */
    public void setMenuIndex(String menuIndex) {
        this.menuIndex = menuIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.icon
     *
     * @return the value of sys_right.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.icon
     *
     * @param icon the value for sys_right.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.description
     *
     * @return the value of sys_right.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.description
     *
     * @param description the value for sys_right.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.creation_time
     *
     * @return the value of sys_right.creation_time
     *
     * @mbg.generated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.creation_time
     *
     * @param creationTime the value for sys_right.creation_time
     *
     * @mbg.generated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.creation_user_id
     *
     * @return the value of sys_right.creation_user_id
     *
     * @mbg.generated
     */
    public Long getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.creation_user_id
     *
     * @param creationUserId the value for sys_right.creation_user_id
     *
     * @mbg.generated
     */
    public void setCreationUserId(Long creationUserId) {
        this.creationUserId = creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.last_update_time
     *
     * @return the value of sys_right.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.last_update_time
     *
     * @param lastUpdateTime the value for sys_right.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.last_update_user_id
     *
     * @return the value of sys_right.last_update_user_id
     *
     * @mbg.generated
     */
    public Long getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.last_update_user_id
     *
     * @param lastUpdateUserId the value for sys_right.last_update_user_id
     *
     * @mbg.generated
     */
    public void setLastUpdateUserId(Long lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }
    
}