package com.roger.ims.mapper;

import com.roger.ims.entity.SysUser;
import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    List<SysUser> selectAll();
    
	/**
	 * 根据登录账户查询 
	 */
    SysUser selectByLoginName(String loginName,String password);
    
}