package com.roger.ims.mapper;

import com.roger.ims.entity.SysRole;
import com.roger.ims.entity.SysUser;
import com.roger.ims.vo.UserVo;

import java.util.List;

public interface SysUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user
	 *
	 * @mbg.generated
	 */
	List<SysUser> selectAll();


	/**  
	 * @Title: selectUserInfoByUser
	 * @Description: 根据登录账户查询
	 * @param user
	 * @return  SysUser
	 */  
	SysUser selectUserInfoByUser(SysUser user);
    
	
	List<SysUser> selectUser(UserVo user);
	
	int updateRole(SysRole role);
	
	int deleteRole(List<SysRole> role);
	
	List<SysRole> selectRolesByUser(SysUser user);

}